/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\\public\\beach_rock.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function BeachRock(props) {
  const { nodes, materials } = useGLTF('/beach_rock.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-0.348, 0.065, -0.022]} rotation={[0.708, 1.492, -2.21]}>
        <group position={[-0.329, 0.891, -0.2]}>
          <mesh geometry={nodes.Object_3.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.material_0} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/beach_rock.glb')
