/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\\public\\boat_josefa.glb 
Author: Alexandre González Rivas (https://sketchfab.com/AlexandreGonzalezRivas)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/boat-josefa-90f8077289544059b03f974efeda6093
Title: Boat "Josefa"
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
type boatType={
  scale:number,
  position:[number,number,number],
}
export function Boat(props:boatType) {
  const { nodes, materials } = useGLTF('/cafe-3d/boat_josefa.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={(nodes.Object_2  as THREE.Mesh).geometry} material={materials.barco_con_low_Material_u1_v1} rotation={[-Math.PI / 2, 0, 0]} scale={0.59} />
    </group>
  )
}

useGLTF.preload('/boat_josefa.glb')
