/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/broken_row_boat.glb 
*/

import { useGLTF } from '@react-three/drei'
type BrokenBoatType={
  scale:number,
  position:[number,number,number]
}
export function BrokenBoat({scale,position}:BrokenBoatType) {
  const { nodes, materials } = useGLTF('/broken_row_boat.glb')
  return (
    <group scale={scale} position={position} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials.DefaultMaterial} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/broken_row_boat.glb')
