/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\\public\\cafe-misti.glb 
*/
import { useGLTF } from '@react-three/drei'

export function CafeMisti(props) {
  const { nodes, materials } = useGLTF('/cafe-misti.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.011}>
       <mesh geometry={nodes.Object_2.geometry} material={materials.Abstract_Blue_Square} />
          <mesh geometry={nodes.Object_3.geometry} material={materials.Base} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Base} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.Body_Black_1} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.Color_B01} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.Cromado} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.Custom} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.Material_1} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.Material__2} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.Material__4} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.Material__6} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.No_12} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.No_34} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.No_68} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.PENNY_TILE} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.Plasticos} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.Translucent_Glass_Green_Dark} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['3D_Print_Gray']} />
        <mesh geometry={nodes.Object_21.geometry} material={materials['3D_Print_White']} />
        <mesh geometry={nodes.Object_22.geometry} material={materials.material_19} />
        <mesh geometry={nodes.Object_23.geometry} material={materials.material_19} />
        <mesh geometry={nodes.Object_24.geometry} material={materials.material_19} />
        <mesh geometry={nodes.Object_25.geometry} material={materials.Aluminum_Anodized_Clear} />
        <mesh geometry={nodes.Object_26.geometry} material={materials.Aluminum_Anodized_Clear_1} />
        <mesh geometry={nodes.Object_27.geometry} material={materials.Aluminum_Anodized_DarkGray} />
        <mesh geometry={nodes.Object_28.geometry} material={materials.Aluminum_Anodized_DarkGray} />
        <mesh geometry={nodes.Object_29.geometry} material={materials.Aluminum_Blurry} />
        {/* <mesh geometry={nodes.Object_30.geometry} material={materials.Asphalt_C01_100cm} />  Road*/} 
        <mesh geometry={nodes.Object_31.geometry} material={materials.CONC_LIGHT} />
        <mesh geometry={nodes.Object_32.geometry} material={materials.Fabric_B01_20cm} />
        <mesh geometry={nodes.Object_33.geometry} material={materials.Fabric_C01_20cm} />
        <mesh geometry={nodes.Object_34.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Object_35.geometry} material={materials.Glass_Bumpy_02_10cm} />
        <mesh geometry={nodes.Object_36.geometry} material={materials.Glass_Frosted} />
        {/* <mesh geometry={nodes.Object_37.geometry} material={materials.Glass_Tinted_Black} /> Iron bar */}
        <mesh geometry={nodes.Object_38.geometry} material={materials.Grass_A_200cm} />
        <mesh geometry={nodes.Object_39.geometry} material={materials.Paper_A_20cm} />
        <mesh geometry={nodes.Object_40.geometry} material={materials.Paper_C02_8cm} />
        <mesh geometry={nodes.Object_41.geometry} material={materials.Porcelain_B01_White_10cm} />
        <mesh geometry={nodes.Object_42.geometry} material={materials.Soil_B01_200cm} />
        <mesh geometry={nodes.Object_43.geometry} material={materials.Stone_E_150cm} />
        <mesh geometry={nodes.Object_44.geometry} material={materials.Tiles_G_200cm} />
        <mesh geometry={nodes.Object_45.geometry} material={materials.Tiles_L01_2m} />
        <mesh geometry={nodes.Object_46.geometry} material={materials.Veneer_D02_120cm} />
        <mesh geometry={nodes.Object_47.geometry} material={materials.Veneer_D02_120cm} />
        <mesh geometry={nodes.Object_48.geometry} material={materials.WallPaint_FineGrain_01_White_1m} />
        <mesh geometry={nodes.Object_49.geometry} material={materials.coffeecover} />
        <mesh geometry={nodes.Object_50.geometry} material={materials.diffuse_0} />
        <mesh geometry={nodes.Object_51.geometry} material={materials.glass_bulb} />
        <mesh geometry={nodes.Object_52.geometry} material={materials.il_fullxfull_1123419681_6ucv} />
        <mesh geometry={nodes.Object_53.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_54.geometry} material={materials.menu} />
        <mesh geometry={nodes.Object_55.geometry} material={materials.metal_dark} /> */}
      </group>
    </group>
  )
}

useGLTF.preload('/cafe-misti.glb')
