/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\\public\\cozy_morning_in_a_cafe__3d_editor_challenge.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
type CafeType={
  scale:number,
  position:[number,number,number]
}
export function Cafe({scale,position}:CafeType) {
  const { nodes, materials } = useGLTF('/cozy_morning_in_a_cafe__3d_editor_challenge.glb')
  return (
    <group scale={scale} position={position} dispose={null}>
      <group position={[-0.972, 0, -0.96]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_8.geometry} material={materials.chara} position={[-2.531, 1.034, -2.24]} rotation={[Math.PI / 2, 0, -0.763]} scale={1.752} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.Items} position={[1.111, 0.735, -0.676]} rotation={[-Math.PI, -0.31, -Math.PI]} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.Items} position={[-1.719, 0.735, 0.212]} rotation={[0, 1.428, 0]} />
          <mesh geometry={nodes.Object_17.geometry} material={materials.Items_specular} position={[0.927, 1.012, -2.5]} rotation={[0, -Math.PI / 2, 0]} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.Items} position={[0.923, 0.735, -0.4]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.Object_23.geometry} material={materials.Items} position={[0.945, 0.735, -0.969]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.Object_26.geometry} material={materials.Items} position={[-1.996, 0.735, 0.172]} rotation={[0, 1.428, 0]} />
          <mesh geometry={nodes.Object_29.geometry} material={materials.Items} position={[-1.48, 0.735, 0.242]} rotation={[0, 1.428, 0]} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.Items_specular} position={[0.753, 1.012, -2.653]} scale={1.015} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.Items} position={[0.79, 0.735, -0.664]} rotation={[-Math.PI, 0, -Math.PI]} />
          <mesh geometry={nodes.Object_38.geometry} material={materials.Items} position={[-1.845, 0.735, 0.385]} rotation={[0, 1.428, 0]} />
          <mesh geometry={nodes.Object_41.geometry} material={materials.Items} position={[0.365, 1.012, -2.539]} />
          <mesh geometry={nodes.Object_44.geometry} material={materials.Background} position={[1.902, 1.722, -0.71]} />
          <mesh geometry={nodes.Object_47.geometry} material={materials.Items_baked} position={[-1.377, 0, -1.82]} rotation={[-Math.PI, -0.682, -Math.PI]} />
          <mesh geometry={nodes.Object_50.geometry} material={materials.Building_Baked} position={[0.679, 0, -0.705]} rotation={[-Math.PI, 0, -Math.PI]} />
          <group position={[-2.765, 1.647, -3.884]}>
            <mesh geometry={nodes.Object_53.geometry} material={materials.Items} />
            <mesh geometry={nodes.Object_55.geometry} material={materials['Items_emission.001']} />
            <mesh geometry={nodes.Object_57.geometry} material={materials.Desserts} />
            <mesh geometry={nodes.Object_59.geometry} material={materials.Foliage} />
            <mesh geometry={nodes.Object_61.geometry} material={materials.FoliageNoSpecular} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cozy_morning_in_a_cafe__3d_editor_challenge.glb')
