/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\\public\\eroded_sand_edge_on_rugen_beach__realityscan.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
type BeachType={
  scale:number,
  position:[number,number,number]
}
export function Beach({scale,position}:BeachType) {
  const { nodes, materials } = useGLTF('/eroded_sand_edge_on_rugen_beach__realityscan.glb')
  return (
    <group scale={scale} position={position} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.model_tex_u1_v1_0.geometry} material={materials.tex_u1_v1} />
          <mesh geometry={nodes.model_tex_u1_v1_0_1.geometry} material={materials.tex_u1_v1} />
          <mesh geometry={nodes.model_tex_u1_v1_0_2.geometry} material={materials.tex_u1_v1} />
          <mesh geometry={nodes.model_tex_u1_v1_0_3.geometry} material={materials.tex_u1_v1} />
          <mesh geometry={nodes.model_tex_u1_v1_0_4.geometry} material={materials.tex_u1_v1} />
          <mesh geometry={nodes.model_tex_u1_v1_0_5.geometry} material={materials.tex_u1_v1} />
          <mesh geometry={nodes.model_tex_u1_v1_0_6.geometry} material={materials.tex_u1_v1} />
          <mesh geometry={nodes.model_tex_u1_v1_0_7.geometry} material={materials.tex_u1_v1} />
          <mesh geometry={nodes.model_tex_u1_v1_0_8.geometry} material={materials.tex_u1_v1} />
          <mesh geometry={nodes.model_tex_u1_v1_0_9.geometry} material={materials.tex_u1_v1} />
          <mesh geometry={nodes.model_tex_u1_v1_0_10.geometry} material={materials.tex_u1_v1} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/eroded_sand_edge_on_rugen_beach__realityscan.glb')
