/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\\public\\frame.glb 
Author: toya_mimura (https://sketchfab.com/toya_mimura)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/frame03-f2a37b4ca65f465fa5bf69f60aaa1f40
Title: Frame03
*/
import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'

export function Frame() {
  const { nodes, materials } = useGLTF('/cafe-3d/frame.glb')
  return (
    <group dispose={null} position={[-2,2,7]} rotation={[0,0,-Math.PI/2]}>
      <mesh geometry={(nodes.Plane001_Material003_0 as THREE.Mesh).geometry} material={materials['Material.003']} position={[0, -0.001, 0.039]} scale={[0.072, 0.091, 0.09]} />
    </group>
  )
}

useGLTF.preload('/frame.glb')
