/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/glass.glb 
Author: AleixoAlonso (https://sketchfab.com/AleixoAlonso)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/tall-drinking-glass-6e1168814f8d4c44b4a833f41093905a
Title: Tall Drinking Glass
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function Glass() {
  const { nodes, materials } = useGLTF('/cafe-3d/glass.glb')
  return (
    <group  dispose={null} position={[-0.85,1.65,15.65]} >
      <group rotation={[-Math.PI / 2, 0, 0]} scale={1.051}>
        <mesh geometry={(nodes.Object_4 as THREE.Mesh).geometry} material={materials.GLS0002_Glass} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/cafe-3d/glass.glb')
