/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/pan.glb 
*/
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import { useRef } from 'react'
import * as THREE from 'three'

export function Pan() {
  const { nodes, materials } = useGLTF('/cafe-3d/pan.glb')
  const panRef=useRef<THREE.Group|null>(null)
  useFrame(({ clock }) => {
    if (panRef.current) {
      panRef.current.position.x = Math.sin(clock.getElapsedTime()*3) * 1; // Moves left & right
    }
  });
  
  
  return (
    <group dispose={null}scale={0.1} position={[-3.25,1.85,20.6]}  >
      <group scale={0.01} ref={panRef}>
        <group rotation={[-Math.PI/2, 0, 0]} scale={[94.073, 94.073, 104.525]}>
          <group position={[3.455, 0, 0.845]} rotation={[0, -0.263, 0]} scale={[1.056, 1.063, 0.964]}>
            <mesh geometry={(nodes.MainHandle_Plastic_0  as THREE.Mesh).geometry} material={materials.Plastic} />
            <mesh geometry={(nodes.MainHandle_Metal_0 as THREE.Mesh).geometry} material={materials.Metal} />
          </group>
          <mesh geometry={(nodes.Pan_PanIns_0 as THREE.Mesh).geometry} material={materials.PanIns} />
          <mesh geometry={(nodes.Pan_Material_0 as THREE.Mesh).geometry} material={materials.Material} />
          <mesh geometry={(nodes.Pan_RedMetal_0 as THREE.Mesh).geometry} material={materials.RedMetal} />
        </group>
        <group position={[0, 110.227, 0.111]} rotation={[-Math.PI / 2, 0, 0]} scale={100}  >
          <group position={[0, 0.001, -0.36]} scale={[0.896, 0.896, 0.184]}>
            <mesh geometry={(nodes.Cover_Material001_0 as THREE.Mesh).geometry} material={materials['Material.001']} />
            <mesh geometry={(nodes.Cover001_Material005_0 as THREE.Mesh).geometry} material={materials['Material.005']} position={[0, 0, -0.522]} />
          </group>
          <mesh geometry={(nodes.Handle_Plastic_0 as THREE.Mesh).geometry} material={materials.Plastic} />
          <mesh geometry={(nodes.Handle_Metal_0 as THREE.Mesh).geometry} material={materials.Metal} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cafe-3d/pan.glb')
