/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/plate.glb 
Author: Valter Medeiros (https://sketchfab.com/valumlab)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/plate-3966eab192da44d7ad1e1c9d0afb08d5
Title: Plate
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function Plate() {
  const { nodes, materials } = useGLTF('/cafe-3d/plate.glb')
  return (
    <group dispose={null} position={[-0.6,1.65,15.65]} scale={0.003}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={2.54}>
        <mesh geometry={(nodes['Prato_Material_#25_0'] as THREE.Mesh).geometry} material={materials.Material_25} position={[0, 0, 3.186]} />
      </group>
    </group>
  )
}

useGLTF.preload('/cafe-3d/plate.glb')
