/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\\public\\porta_menu_b.glb 
Author: KREION (https://sketchfab.com/kreion)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/porta-menu-b-dea38789b813434a91fea055b418d020
Title: Porta menu b
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/porta_menu_b.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[43.826, -0.008, 13.622]} scale={[0.116, 1, 0.116]}>
          <mesh geometry={nodes.Material2_1.geometry} material={materials.Color_M00} />
          <mesh geometry={nodes.Material2_2.geometry} material={materials.Color_M00} />
          <mesh geometry={nodes.Material2_3.geometry} material={materials.Color_M00} />
          <mesh geometry={nodes.Material2_4.geometry} material={materials.Color_M00} />
          <mesh geometry={nodes.Material2_5.geometry} material={materials.Color_M00} />
          <mesh geometry={nodes.Material2_6.geometry} material={materials.Color_M00} />
          <mesh geometry={nodes.Material2_7.geometry} material={materials.Color_M00} />
          <mesh geometry={nodes.Material2_8.geometry} material={materials.Color_M00} />
          <mesh geometry={nodes.Material2_9.geometry} material={materials.Color_M00} />
          <mesh geometry={nodes.Material2_10.geometry} material={materials.Color_M00} />
          <mesh geometry={nodes.Material2_11.geometry} material={materials.Color_M00} />
          <mesh geometry={nodes.Material2_12.geometry} material={materials.Color_M00} />
          <mesh geometry={nodes.Material2_13.geometry} material={materials.Color_M00} />
          <mesh geometry={nodes.Material2_14.geometry} material={materials.Color_M00} />
          <mesh geometry={nodes.Material2_15.geometry} material={materials.Color_M00} />
          <mesh geometry={nodes.Material2_16.geometry} material={materials.Color_C05} />
          <mesh geometry={nodes.Material2_17.geometry} material={materials.Color_M00} />
          <mesh geometry={nodes.Material2_18.geometry} material={materials.Color_M00} />
          <mesh geometry={nodes.Material2_19.geometry} material={materials.Color_M00} />
          <mesh geometry={nodes.Material2_20.geometry} material={materials.Color_M00} />
          <mesh geometry={nodes.Material2_21.geometry} material={materials.Color_C05} />
          <mesh geometry={nodes.Material2_22.geometry} material={materials.Color_C05} />
        </group>
        <group position={[46.024, -0.827, 0.197]}>
          <mesh geometry={nodes.Material2_23.geometry} material={materials.material} />
          <mesh geometry={nodes.Material2_24.geometry} material={materials['Scheda-Google-My-Business-di-PanB-Oriocenter-sezione-galleria-immagini']} />
        </group>
        <group position={[46.024, -0.512, 0.197]}>
          <mesh geometry={nodes.Material2_25.geometry} material={materials.material} />
          <mesh geometry={nodes.Material2_26.geometry} material={materials['Scheda-Google-My-Business-di-PanB-Oriocenter-sezione-galleria-immagini']} />
        </group>
        <group position={[46.024, -0.354, 0.197]}>
          <mesh geometry={nodes.Material2_27.geometry} material={materials.material} />
          <mesh geometry={nodes.Material2_28.geometry} material={materials['Scheda-Google-My-Business-di-PanB-Oriocenter-sezione-galleria-immagini']} />
        </group>
        <group position={[39.803, -0.512, 0.197]}>
          <mesh geometry={nodes.Material2_30.geometry} material={materials.material} />
          <mesh geometry={nodes.Material2_31.geometry} material={materials['Scheda-Google-My-Business-di-PanB-Oriocenter-sezione-galleria-immagini']} />
        </group>
        <group position={[39.803, -0.433, 0.197]}>
          <mesh geometry={nodes.Material2_32.geometry} material={materials.material} />
          <mesh geometry={nodes.Material2_33.geometry} material={materials['Scheda-Google-My-Business-di-PanB-Oriocenter-sezione-galleria-immagini']} />
        </group>
        <group position={[46.024, -0.276, 0.197]}>
          <mesh geometry={nodes.Material2_34.geometry} material={materials.material} />
          <mesh geometry={nodes.Material2_35.geometry} material={materials['Scheda-Google-My-Business-di-PanB-Oriocenter-sezione-galleria-immagini']} />
        </group>
        <group position={[46.024, -0.669, 0.197]}>
          <mesh geometry={nodes.Material2_36.geometry} material={materials.material} />
          <mesh geometry={nodes.Material2_37.geometry} material={materials['Scheda-Google-My-Business-di-PanB-Oriocenter-sezione-galleria-immagini']} />
        </group>
        <group position={[46.024, -0.748, 0.197]}>
          <mesh geometry={nodes.Material2_38.geometry} material={materials.material} />
          <mesh geometry={nodes.Material2_39.geometry} material={materials['Scheda-Google-My-Business-di-PanB-Oriocenter-sezione-galleria-immagini']} />
        </group>
        <group position={[39.803, -0.276, 0.197]}>
          <mesh geometry={nodes.Material2_40.geometry} material={materials.material} />
          <mesh geometry={nodes.Material2_41.geometry} material={materials['Scheda-Google-My-Business-di-PanB-Oriocenter-sezione-galleria-immagini']} />
        </group>
        <group position={[46.024, -0.433, 0.197]}>
          <mesh geometry={nodes.Material2_42.geometry} material={materials.material} />
          <mesh geometry={nodes.Material2_43.geometry} material={materials['Scheda-Google-My-Business-di-PanB-Oriocenter-sezione-galleria-immagini']} />
        </group>
        <group position={[39.803, -0.591, 0.197]}>
          <mesh geometry={nodes.Material2_44.geometry} material={materials.material} />
          <mesh geometry={nodes.Material2_45.geometry} material={materials['Scheda-Google-My-Business-di-PanB-Oriocenter-sezione-galleria-immagini']} />
        </group>
        <group position={[46.024, -0.591, 0.197]}>
          <mesh geometry={nodes.Material2_46.geometry} material={materials.material} />
          <mesh geometry={nodes.Material2_47.geometry} material={materials['Scheda-Google-My-Business-di-PanB-Oriocenter-sezione-galleria-immagini']} />
        </group>
        <group position={[39.803, -0.354, 0.197]}>
          <mesh geometry={nodes.Material2_48.geometry} material={materials.material} />
          <mesh geometry={nodes.Material2_49.geometry} material={materials['Scheda-Google-My-Business-di-PanB-Oriocenter-sezione-galleria-immagini']} />
        </group>
        <mesh geometry={nodes.Material2.geometry} material={materials.Color_M08} position={[39.37, -1.181, 0]} />
        <mesh geometry={nodes.Material2_29.geometry} material={materials.Translucent_Glass_Blue} position={[39.37, -1.181, -2.677]} />
      </group>
    </group>
  )
}

useGLTF.preload('/porta_menu_b.glb')
