/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/radio.glb 
Author: Royd45 (https://sketchfab.com/Royd45)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/soviet-radio-quartz-404-c4bd6f3748b04a8da7c81be5733f9c77
Title: Soviet Radio Quartz - 404
*/
import * as THREE from 'three'
import { Text, useGLTF } from '@react-three/drei'
type RadioType={
  handlePlay:()=>void
  handlePause:()=>void
  audioStatus:string
}

export function Radio({handlePlay,handlePause,audioStatus}:RadioType) {
  const { nodes, materials } = useGLTF('/cafe-3d/radio.glb')
  
  return (
    <group  dispose={null} position={[0.5,1.9,18]} rotation={[-Math.PI,0,Math.PI]} >
      <group position={[-0.001, 0, -0.008]} scale={[0.086, 0.048, 0.014]}>
        <mesh geometry={(nodes.Object_4 as THREE.Mesh).geometry} material={materials.RadioBody} />
        <mesh geometry={(nodes.Object_5 as THREE.Mesh).geometry} material={materials.Chrome} />
      </group>
      <group position={[0.069, 0.023, 0.018]}>
        <mesh geometry={(nodes.Object_9 as THREE.Mesh).geometry} material={materials.RadioBody} />
        <mesh geometry={(nodes.Object_10 as THREE.Mesh).geometry} material={materials.Chrome} />
      </group>
      <group position={[0.069, -0.01, 0.018]}>
        <mesh geometry={(nodes.Object_12 as THREE.Mesh).geometry} material={materials.RadioBody} />
        <mesh geometry={(nodes.Object_13 as THREE.Mesh).geometry} material={materials.Chrome} />
      </group>
      <mesh geometry={(nodes.Object_7 as THREE.Mesh).geometry} material={materials.RadioBody} position={[0, 0.008, -0.029]} scale={[0.071, 0.027, 0.007]} />
      <Text scale={0.005} position={[0.067,0.023,0.0255]} onClick={()=>{handlePlay()}} onPointerOver={()=>{}}>Upload</Text>
      <Text scale={0.005} position={[0.067,-0.009,0.0255]} onClick={()=>{handlePause()}}>{audioStatus}</Text>
    </group>
  )
}

useGLTF.preload('/radio.glb')
