/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/soup.glb 
Author: mornaista (https://sketchfab.com/mornaista)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bowl-with-soup-de4ecf2c5040488ab98d214a0d9362cc
Title: Bowl with Soup
*/
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'

export function Soup() {
  const { nodes, materials } = useGLTF('/cafe-3d/soup.glb')
  return (
    <group position={[-0.6,1.65,15.65]} scale={0.003} dispose={null}>
      <group position={[0, 23.029, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={31.2}>
        <mesh geometry={(nodes.T_Bowl_Soup_T_Soup_0 as THREE.Mesh).geometry} material={materials.T_Soup} />
        <mesh geometry={(nodes.T_Bowl_Soup_M_Bowl_Empty_0 as THREE.Mesh).geometry} material={materials.M_Bowl_Empty} />
      </group>
    </group>
  )
}

useGLTF.preload('/cafe-3d/soup.glb')
